"""Replace barcode field with separate UPC and ISBN fields

Revision ID: 2c45a4ae4f8f
Revises: 1729b8031f66
Create Date: 2025-08-25 22:26:44.587747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c45a4ae4f8f'
down_revision = '1729b8031f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upc', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('isbn', sa.String(length=20), nullable=True))
        batch_op.drop_column('barcode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('isbn')
        batch_op.drop_column('upc')

    # ### end Alembic commands ###
