"""Add series and issue_title fields to Comic model

Revision ID: 44015114bd6c
Revises: 2c45a4ae4f8f
Create Date: 2025-08-27 17:37:24.793000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44015114bd6c'
down_revision = '2c45a4ae4f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('issue_title', sa.String(length=200), nullable=True))
        batch_op.alter_column('cover_image',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.alter_column('cover_image',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('issue_title')
        batch_op.drop_column('series')

    # ### end Alembic commands ###
